DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS scores;
DROP TABLE IF EXISTS ranges;
DROP TABLE IF EXISTS questions;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE scores (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    score INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user (id)
);

CREATE TABLE ranges(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    min INTEGER NOT NULL,
    max INTEGER NOT NULL,
    definition TEXT NOT NULL
);

CREATE TABLE questions(
    scoreId INTEGER PRIMARY KEY,
    q1 INTEGER NOT NULL,
    q2 INTEGER NOT NULL,
    q3 INTEGER NOT NULL,
    q4 INTEGER NOT NULL,
    q5 INTEGER NOT NULL,
    q6 INTEGER NOT NULL,
    q7 INTEGER NOT NULL,
    q8 INTEGER NOT NULL,
    q9 INTEGER NOT NULL,
    q10 INTEGER NOT NULL,
    q11 INTEGER NOT NULL,
    q12 INTEGER NOT NULL,
    q13 INTEGER NOT NULL,
    q14 INTEGER NOT NULL,
    q15 INTEGER NOT NULL,
    q16 INTEGER NOT NULL,
    q17 INTEGER NOT NULL,
    q18 INTEGER NOT NULL,
    q19 INTEGER NOT NULL,
    q20 INTEGER NOT NULL,
    q21 INTEGER NOT NULL,
    FOREIGN KEY (scoreId) REFERENCES scores (id)
)
